language: node_js
node_js:
  - "11"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run chk:data
  - npm run prettier
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  keep_history: false
  fqdn: claviers-mecaniques.org
  on:
    branch: master
